# Fichero encargado de arrancar el backend y todas sus dependencias autom치ticamente

version: '3.3'
services:
  backend-database:
    image: 'postgres:14-alpine'
    container_name: 'ticket-manager-database'
    # [Puerto que abrimos en nuestra m치quina]:[Puerto al que queremos acceder en el contenedor]
    ports:
      - "5432:5432"       # Abrimos el localhost:5432 para evitar problemas si tenemos Postgres instalado
    #networks:
    #  - backend-network
    # Variables de entorno del contenedor
    environment:
      POSTGRES_USER: postgres                 # Nombre del usuario por defecto en la BD
      POSTGRES_PASSWORD: password             # Contrase침a para acceder a la BD
      POSTGRES_DB: production                 # Nombre de la base de datos creada por defecto en la BD
    user: postgres

    # Crear las tablas tan pronto se arranque el contenedor
    # https://levelup.gitconnected.com/creating-and-filling-a-postgres-db-with-docker-compose-e1607f6f882f
    volumes:
      # Ficheros SQL dentro de docker-entrypoint-initdb.d se ejecutan autom치ticamente al arrancar el contenedor
      - ./target/classes/database-schema.sql:/docker-entrypoint-initdb.d/database-schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 10s
      retries: 3

