# Fichero con la configuración para el entorno de desarrollo
logging:
  level:
    org:
      hibernate:
        SQL: debug    # Mostrar parámetros en consultas SQL generadas por Hibernate


# Es necesario ejecutar 'docker-compose up -d' sobre el fichero src/main/docker/docker-compose.dev.yml
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5430/development"
    username: postgres
    password: password
